In [ ]:
!pip install sklearn

Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [ ]:
import pandas as pd

train = pd.read_csv("train.csv", index_col=0).rename(columns={'MedHouseVal': 'target'})
train.describe()

             MedInc      HouseAge  ...     Longitude        target
count  37137.000000  37137.000000  ...  37137.000000  37137.000000
mean       3.851029     26.057005  ...   -119.554329      2.079751
std        1.803167     12.158221  ...      1.974028      1.158571
min        0.499900      2.000000  ...   -124.350000      0.149990
25%        2.602300     17.000000  ...   -121.800000      1.208000
50%        3.515600     25.000000  ...   -118.450000      1.808000
75%        4.699700     35.000000  ...   -118.020000      2.660000
max       15.000100     52.000000  ...   -114.550000      5.000010

[8 rows x 9 columns]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(train.drop(columns=['target']), train['target'], test_size=0.3, random_state=42)

In [ ]:
X_train

       MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
id                                 ...
17647  4.9643      33.0  5.649425  ...  2.826271     34.04    -118.48
11010  4.7946      13.0  7.337500  ...  2.690972     38.65    -121.36
35733  4.7094      13.0  6.527646  ...  2.935860     33.83    -117.21
6552   5.8898      16.0  6.205937  ...  3.291809     34.22    -118.88
17191  2.3456      11.0  3.371642  ...  2.539735     34.16    -118.37
...       ...       ...       ...  ...       ...       ...        ...
16850  2.7797      35.0  4.539378  ...  3.128959     37.35    -121.86
6265   3.0481      39.0  5.930000  ...  2.738750     35.34    -119.01
11284  3.6346      33.0  5.010462  ...  2.263598     37.65    -122.43
860    2.1979      21.0  4.722298  ...  2.432316     34.58    -117.41
15795  2.1449      21.0  5.017953  ...  2.072797     38.49    -121.50

[25995 rows x 8 columns]

In [ ]:
# print(y_train.head())

print(y_train.columns)

AttributeError: 'Series' object has no attribute 'columns'